name: Maven Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
