name: Maven Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  
jobs:
  release:
    strategy:
      matrix:
        java-version: [ 21 ]
        distribution: [ temurin ]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:          
            fetch-depth: 0
        - name: bot user
          run: git config user.name "${{ github.actor }}"
        - uses: actions/setup-java@v4.7.1
          with:
            java-version: ${{ matrix.java-version }}
            distribution: ${{ matrix.distribution }}
            cache: 'maven'
        - name: release - prepare
          run: mvn -B release:prepare
        - name: release - perform (publish)
          run: mvn release:perform
          
