name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  call-release:
    uses: akil-rails/shared-github-workflows/.github/workflows/release.yml@main
    secrets:
      PAT: ${{ secrets.PAT }}
